### ISSUE TITLE
Differ layout and content editions on Pages Editor 

### ISSUE THREAD

**Issue by gabrielgalc** [vtex-apps/pages-editor#22]
## The frequency of layout and content editions are not equal, so it should have different displays.
People change banners more often than change the container height.

## Current Behavior
Layout and content form inputs are being displayed the same way with the same hierarchy.

## Possible Solution
Create tabs of "layout" and "content", for example. Filter them by profile. Differ only layout.

**Comment by pedroteosousa** [comment]
Closed with #30
